### ISSUE TITLE
Log statements are not grouped to parent request in App Engine Standard P3

### ISSUE THREAD

**Issue by MeLight** [googleapis/python-logging#110]
#### Environment details

  - OS type and version: App Engine Python 3 Standard
#### Steps to reproduce

  1. Add couple of logging statements 
  2. Go to Logs Explorer on your cloud console

#### Code example

```python
import google.cloud.logging
import logging

client = google.cloud.logging.Client()

client.get_default_handler()
client.setup_logging()

logging.info("Testing lines")
logging.info("Again!")
```

Result:
![image](https://user-images.githubusercontent.com/704484/100991402-9f8c4c00-355b-11eb-84f5-a3ed45152d59.png)
As you can see every statement is on it's own line, as opposed to what's expected - the statements should be grouped under one log like in App Engine Standard Python2
![image](https://user-images.githubusercontent.com/704484/100995719-d1ec7800-3560-11eb-967a-2dbaba2bd681.png)

How to group the statements to the parent request?

**Comment by snarfed** [comment]
I'm also seeing this, no matter what I try. Looks like it's the default with google-cloud-logging 2.0 on App Engine Standard: the built in Python root logger sends to Cloud Logging, with resource type `gae_app` and log name `projects/brid-gy/logs/app` - good! - but those log lines aren't attached and rendered with the `appengine.googleapis.com/request_log` log entry.

I first noticed this change when I migrated to App Engine Python 3 a while back. I managed to fix it for google-cloud-logging 1.x with the code below, [which I found here](https://stackoverflow.com/a/58296028/186123):

```
import google.cloud.logging
from google.cloud.logging_v2.handlers import AppEngineHandler, setup_logging
logging_client = google.cloud.logging.Client()
setup_logging(AppEngineHandler(logging_client, name='stdout'))
```

... but this no longer works with google-cloud-logging 2.0. I've tried a bunch of variants, including no manual setup at all (ie relying on the [default integration on App Engine](https://cloud.google.com/logging/docs/setup/python#run-gae)), but no luck so far.

**Comment by Daniel-Sanche** [comment]
Thanks the the report. We're working on improving the cross-platform tests to make sure everything's consistent across GCP platforms, and this bug should be fixed by that effort. I'll try to bump of the priority of this one though, and see if I can fix it a bit earlier

What framework are you using for your web server to handle these requests?

**Comment by snarfed** [comment]
Thank you @Daniel-Sanche! Sounds good. I'll also try downgrading to 1.x in the meantime to see if that fixes it.

I'm on [webapp2](https://pypi.org/project/webapp2/) (don't judge 😆), v3.0.0b1 for Python 3 support. [My app is open source.](https://github.com/snarfed/bridgy/) [Here's its current google-cloud-logging setup code.](https://github.com/snarfed/webutil/blob/13e29b99f92eac15cbd6e619fbc0cfa88fbd3332/appengine_config.py#L70-L84)

**Comment by Daniel-Sanche** [comment]
@MeLight 
I tried out a deployment on AppEngine standard today, and I was able to see grouping as normal (although I did see duplicate logs, and I saw the child logs both at the root, and under the request):
![image](https://user-images.githubusercontent.com/3914119/101684125-c4c90080-3a1a-11eb-9220-6ec78c9b4340.png)

[Here's the doumentation](https://github.com/googleapis/google-cloud-go/blob/112bcdeb7cee1b44f337d3e5398a0d0820e93162/logging/doc.go#L116) for how grouping works from the go library. The parent should be created automatically for you on AppEngine. Is the trace id being set properly in your logs? It should be set automatically using flask and django, but it may not be set if you're using a different web framework

**Comment by Daniel-Sanche** [comment]
@snarfed 

Unfortunately I don't think we can fully support webapp2 going forward. They only officially support Python 2, and that's been dropped by GCP libraries going forward. I don't think we can justify maintaining tests/integrations for a library that doesn't officially support Python 3 yet.

What I will do though, is make sure you have a way to manually set the trace id on your logs. I'll work on that today

**Comment by MeLight** [comment]
@Daniel-Sanche thanks for the reply. I'm using Flask. I'm not sure it's set correctly. Where do I check/how do I set the trace?

**Comment by Daniel-Sanche** [comment]
If it's set properly, you should see a trace field as part of your Log Entry payload. Your payload structure should look something like mine from my image. It would be helpful if you could attach a screenshot of your current logs

Currently the trace is set automatically for the library, but I'm working on a feature to let users manually override the value

**Comment by MeLight** [comment]
@Daniel-Sanche nope, no `trace`.
![image](https://user-images.githubusercontent.com/704484/102016997-bf4a1e00-3d6c-11eb-8104-0518d29f7f10.png)

**Comment by snarfed** [comment]
> What I will do though, is make sure you have a way to manually set the trace id on your logs. I'll work on that today

Thanks again for looking at this! Any progress so far? Let me know if there's anything I can do to help.

**Comment by Daniel-Sanche** [comment]
> nope, no `trace`.

Hmm, and you said you're using flask on App Engine Standard? And you ran `client.setup_logging()`? That should automatically add trace ids to your logs. If you can share some more code with me I can try to debug further.

The root of your issue is that the trace ids aren't being added. If we can solve that, you should start seeing the grouping work as expected

**Comment by Daniel-Sanche** [comment]
> Thanks again for looking at this! Any progress so far? Let me know if there's anything I can do to help.

I opened two PRs around this (https://github.com/googleapis/python-logging/pull/120, https://github.com/googleapis/python-logging/pull/129), when they are merged, you will be able to add traces manually: 
```
trace_header = webapp2.get_request().headers.get("X-CLOUD-TRACE-CONTEXT")
trace_id = trace_header.split("/", 1)[0]

logging.info('log test', extra={'trace':trace_id})
```

Unfortunately with the holidays coming up, we're going to be on a release freeze soon, so I likely won't be able to push the release until January

**Comment by snarfed** [comment]
Thanks @Daniel-Sanche! I tried this just now, using your sample code, but it didn't seem to work. Log browser (legacy) screenshot below, app log entry above, HTTP request below. I see the trace id in the HTTP request, and I emitted the trace id attached in `extra` in the the app log line, and they match, but I don't see it in the app log's fields. Should I?

![image](https://user-images.githubusercontent.com/778068/102940806-04a1d600-4466-11eb-9dc5-f8d07f6ce691.png)

Here's my `setup_logging` invocation:

```py
    from google.cloud.logging.handlers import AppEngineHandler, setup_logging
    setup_logging(AppEngineHandler(logging_client, name='stdout'),
                  log_level=logging.DEBUG)
```

**Comment by snarfed** [comment]
(I installed your PR with `git+https://github.com/snarfed/python-logging.git@manual_data#egg=manual_data` in `requirements.txt`.)

**Comment by snarfed** [comment]
I've downgraded to 1.15.1 for now. We can figure out explicit trace id in the new year!

**Comment by snarfed** [comment]
Fwiw, I just noticed that this is also tracked (I guess?) in https://issuetracker.google.com/issues/118770775.

**Comment by snarfed** [comment]
Figured out my problem. I was still using `AppEngineHandler`, which seemed not to cooperate with the new `extra` kwarg. When I dropped that and switched to a plain vanilla logging client, it worked. Looking at `AppEngineHandler.emit`, if the trace id in extra ends up in `record.trace`, it seems like it should still be ok, but evidently not. 🤷 

I'll also plug @oittaa's https://github.com/googleapis/python-logging/issues/149#issuecomment-782693201 for lifting `X-Cloud-Trace-Context` into the log record's trace id automatically, I'd obviously prefer that too!

**Comment by snarfed** [comment]
Here's the shim log handler class I added that extracts the trace header from webapp2:

```py
class Webapp2TraceHandler(AppEngineHandler):
  """Log handler that adds trace id based on webapp2 request header.

  https://github.com/googleapis/python-logging/issues/110#issuecomment-745534629
  https://github.com/googleapis/python-logging/issues/149#issuecomment-782693201

  Also note that AppEngineHandler is evidently deprecated, so I may need to
  port that whole class into webutil eventually. :(
  https://github.com/googleapis/python-logging/issues/202
  """
  def emit(self, record):
    try:
      import webapp2
      trace = webapp2.get_request().headers.get('X-Cloud-Trace-Context')
      if trace:
        trace_id = trace.split('/', 1)[0]
        record.trace = f'projects/{APP_ID}/traces/{trace_id}'
    except (ImportError, AssertionError):
      pass

    return super().emit(record)
```
