### ISSUE TITLE
 handlers is not accessible from`google.cloud.logging`

### ISSUE THREAD

**Issue by nsteinmetz** [googleapis/python-logging#115]
#### Environment details

  - OS type and version: Linux Fedora 33
  - Python version: 3.9.0
  - pip version: 20.2.2
  - `google-cloud-logging` version: 2.0.1

#### Steps to reproduce

  1. install google-cloud-logging
  2. open a python session in your terminal

#### Code example

handlers is not accessible from`google.cloud.logging` :

```
>>> from google.cloud.logging.handlers import CloudLoggingHandler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'google.cloud.logging.handlers'
```

Whereas it is from `google.cloud.logging_v2` :

```
>>> from google.cloud.logging_v2.handlers import CloudLoggingHandler
>>> 
```
```

**Comment by Daniel-Sanche** [comment]
Good catch. As I commented on your PR, I'd like to fix this one by fixing the import paths for the "logging" alias.

I'd also like to update the tests to use `logging` to make sure we catch other issues like this in the tests
