### ISSUE TITLE
the latest cloud logging >= 2.0.0 does not support 

### ISSUE THREAD

**Issue by hilliao** [googleapis/python-logging#128]
after installing the latest google-cloud-logging 2.0.1, the following logging_v2 client fails:

```
python
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import logging_v2
>>> gcp_logger_v2 = logging_v2.LoggingServiceV2Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'google.cloud.logging_v2' has no attribute 'LoggingServiceV2Client'
>>> 
```

The reason I'd use logging_v2 is that I can specify which log type, project I want to write to. The following is the python 3.8 example:

```
def log(text, severity=LOG_SEVERITY_DEFAULT, log_name=app_name):
    if not severity:
        severity = LOG_SEVERITY_INFO

    gcp_logger_v2 = logging_v2.LoggingServiceV2Client()
    gcp_logger_v2_log_entry = {'log_name': f"projects/{gcp_log_trace_project_id}/logs/{log_name}", 'resource': {
        "type": "global",
        "labels": {
            "project_id": gcp_log_trace_project_id
        }
    }, 'text_payload': text,
                               'severity': severity}

    return gcp_logger_v2.write_log_entries([gcp_logger_v2_log_entry])
```

The code above does not fail on version 1.15.1

**Comment by Daniel-Sanche** [comment]
Hi Hil,

Major releases of our libraries often come with breaking API changes. In this case, the LoggingServiceV2Client [has moved](https://github.com/googleapis/python-logging/blob/master/google/cloud/logging_v2/services/logging_service_v2/client.py). You can now import it with `gcp_logger_v2 = logging_v2.services.logging_service_v2.LoggingServiceV2Client()`

That said, we discourage end users from interacting with the *V2Clients directly. These are auto-generated files, and are often difficult to deal with. I'd advise you to use `logging.Client()` instead:

```
import google.cloud.logging

client = google.cloud.logging.Client()
logger_name = "my_log"
logger = logging_client.logger(logger_name)
logger.log_text('payload text', 
                         severity="WARNING", 
                         resource=google.cloud.logging.Resource(type="global", labels={}))
```
