### ISSUE TITLE
Logging: support sending structured logs to stackdriver via stdlib 'logging'.

### ISSUE THREAD

**Issue by yuvipanda** [googleapis/python-logging#13]
google-cloud-logging version: 1.8.0

I want to send structured logs to stackdriver from Python using the standard logging module. You can integrate structured logging to the Python logging module with either https://github.com/madzak/python-json-logger or http://www.structlog.org/en/stable/. Would be great to preserve those structures as part of `jsonPayload` when sent to stackdriver. Currently, these get stringified and sent as `jsonPayload.message` instead.

**Comment by Voyz** [comment]
Based on @crazystick 's answer, I use the following bodge to log custom objects as info payload. It derives more from the original `_Worker.enqueue` and supports passing custom fields.
```python
from google.cloud.logging import _helpers
from google.cloud.logging.handlers.transports.background_thread import _Worker

def my_enqueue(self, record, message, resource=None, labels=None, trace=None, span_id=None):
    queue_entry = {
        "info": {"message": message, "python_logger": record.name},
        "severity": _helpers._normalize_severity(record.levelno),
        "resource": resource,
        "labels": labels,
        "trace": trace,
        "span_id": span_id,
        "timestamp": datetime.datetime.utcfromtimestamp(record.created),
    }

    if 'custom_fields' in record:
        entry['info']['custom_fields'] = record.custom_fields

    self._queue.put_nowait(queue_entry)

_Worker.enqueue = my_enqueue
```

Then
```python
import logging
from google.cloud import logging as google_logging

logger = logging.getLogger('my_log_client)
logger.addHandler(CloudLoggingHandler(google_logging.Client(), 'my_log_client'))

logger.info('hello', extra={'custom_fields':{'foo': 1, 'bar':{'tzar':3}}})
```

Resulting in:
![image](https://user-images.githubusercontent.com/15874847/73927611-44220b00-4904-11ea-94b4-429418788880.png)

Which then makes it much easier to filter according to these custom_fields.

Naturally, it would be great if this would be naively supported - thanks in advance!

**Comment by mauricepoirrier** [comment]
I tried to implement @Voyz solution on a Cloud Function and I couldn't make it work.
I think there is a strange behaviour with CF and monkey patching the module. 

```python
def my_enqueue(
    self, record, message, resource=None, labels=None, trace=None, span_id=None
):
    queue_entry = {
        "info": {
            "message": message,
            "python_logger": record.name,
            "error_fields": record.error_fields,
        },
        "severity": _helpers._normalize_severity(record.levelno),
        "resource": resource,
        "labels": labels,
        "trace": trace,
        "span_id": span_id,
        "timestamp": datetime.datetime.utcfromtimestamp(record.created),
    }
    self._queue.put_nowait(queue_entry)


_Worker.enqueue = my_enqueue

```
And the function...
```python
def index(request):
    logger = logging.getLogger("my_log_client")
    handler = CloudLoggingHandler(
        logger_client, name="my_log_client", transport=BackgroundThreadTransport
    )
    logger.setLevel(logging.INFO)
    logger.addHandler(handler)
    logging.info("hello")
    logging.info("hello", extra={"custom_one": 1})
    logger.info("hello", extra={"error_fields": {"foo": 1, "bar": {"tzar": 3}}})
    return ("", 202)
```

I would expect some error if `logging.info("hello")` does not have the `error_fields` keys. 
Is there any update if this will be implemented? 

![image](https://user-images.githubusercontent.com/29377393/79504314-b861e480-8000-11ea-97da-9ad06a856b97.png)
No errors :(

**Comment by snickell** [comment]
If you're a `structlog` user and basically just want JSON structlog + GCP to JustWork(TM), I've extended @Voyz / @crazystick 's work, and built a pre-canned gist based on it called `google_structlog`:
https://gist.github.com/snickell/3b664c668b8a94d1ca6e31b0498a8697

Its used like so:
```python
import google_structlog

google_structlog.setup(log_name="here-is-mylilapp")

# Now you can use structlog to get searchable json details in stackdriver...
import structlog
logger = structlog.get_logger()
logger.error("Uhoh, something bad did", moreinfo="it was bad", years_back_luck=5)

# Of course, you can still use plain ol' logging stdlib to get { "message": ... } objects
import logging
logger = logging.getLogger("yoyo")
logger.error("Regular logging calls will work happily too")

# Now you can search stackdriver with the query:
# logName: 'here-is-mylilapp'
```

Which will produce a nice structured / searchable log inside GCP stackdriver:
<img width="1350" alt="Screen Shot 2020-05-21 at 5 31 04 AM" src="https://user-images.githubusercontent.com/223277/82575504-45c6b600-9b24-11ea-9ec6-2ffebad028f8.png">

Main difference with what @Voyz had posted is its somewhat structlog specific, and doesn't care what sort of extra values you pass. It also includes all the pre-canned bells and whistles to run out of the box, and shows you what to search for in GCP so you can work backwards to something that works for you but is working by default.

**Comment by numbsafari** [comment]
Seems like this would be something obvious and *cough* idiomatic to be included in this library. Stack Driver doesn't looks so hot next to Sentry without this capability out of the box.

**Comment by snickell** [comment]
Yeah, its a little frustrating to have "structured logging" with no simple ability to get in on it and inject your own domain-specific fields. That's where structured starts paying for its "not as easy to scan" downsides. The system provided structure fields are sort of 🤷‍♂️ compared to domain specific info that's super easy to create in code, and frustratingly hard to get into the log analysis tools in GCP.

**Comment by numbsafari** [comment]
In my case I'm deploying to GKE, so I needed to modify the GKE handler. I went ahead and copied the approach used by Sentry for extracting the "extra" dictionary, and incorporated things like the python file and line number into a separate dict as well. Works for now.

Perhaps @mauricepoirrier , you need to monkeypatch the ContainerEngineHandler like I did, rather than modifying the transport, in order to get it to work with Cloud Functions?

**Comment by treethought** [comment]
@numbsafari do you have an example of what you did to modify GKE handler?

**Comment by nimish** [comment]
What's the solution here on cloud functions? Using the `google_structlog` hack doesn't send the trace info for some reason and sticks the logs under a different name (fine, but confusing). I'm guessing the log agent on cloud functions does this automatically?

**Comment by snickell** [comment]
I dropped the gist into a repo here:
https://github.com/snickell/google_structlog

Its uploaded to PyPi, so available as:
```
pip install google-structlog
```

**Comment by snickell** [comment]
I'm not using cloud functions, so it'd be really cool if somebody who was could figure out how to make it work "least surprise" in that context too. I'm mostly using python apps running on GKE, for which this works reasonably well for me.

Hopefully somebody at Google will take this off our hands, but until then I think starting with a repo and refining it with issues etc is probably warranted at this level of complexity.

**Comment by nimish** [comment]
> I'm not using cloud functions, so it'd be really cool if somebody who was could figure out how to make it work "least surprise" in that context too. I'm mostly using python apps running on GKE, for which this works reasonably well for me.
> 
> Hopefully somebody at Google will take this off our hands, but until then I think starting with a repo and refining it with issues etc is probably warranted at this level of complexity.

I took a look. It seems like most things the default stdout logger sends can be provided except for trace id. So it's not a huge deal -- the nodejs lib for gcp logging does it -- but it's not complete.

**Comment by caiolopes** [comment]
@snickell your solution is not working for me on Google App Engine, runtime `python37`... Do you have any thoughts on why?

I really enjoy `structlog` lib and was hoping I could use your proposed setup!

Some tests I made: 
```python
import logging
import google_structlog

google_structlog.setup(setup_google=True)

logger = google_structlog.getLogger()
logger.info("Google setup 1")

logger = logging.getLogger()
logger.info("Google setup 2")

print("Google setup 3")
```

![image](https://user-images.githubusercontent.com/4184169/98316467-33004a80-1fb9-11eb-8560-1231910c934c.png)

Doing the proposed setup in here [https://cloud.google.com/logging/docs/setup/python] works, but not for structured data of course

```python
import google.cloud.logging
# Instantiates a client
client = google.cloud.logging.Client()

# Connects the logger to the root logging handler; by default this captures
# all logs at INFO level and higher
client.setup_logging()

logger = logging.getLogger(__name__)
logger.info("Google setup 4")
```

![image](https://user-images.githubusercontent.com/4184169/98317072-845d0980-1fba-11eb-925b-38bd64bed957.png)

**Comment by HynekBlahaDev** [comment]
Hi, I recently came across the issue with structured logging for Google Cloud.
My initial idea was to use structlog with two different renderers: One for console (local development) and one for AppEngine (prod) - inspired by https://github.com/kiwicom/kiwi-structlog-config.

However when I ran it in _app engine standard_, nothing showed up in logs... 🤨

[The official documentation](https://cloud.google.com/logging/docs/setup/python#run-gae) says that everything logged to stdout will be send to Cloud Logging.

```
Note: Logs written to stdout and stderr are automatically sent to Cloud Logging for you, without needing to use Cloud Logging library for Python.
```
I used [this example](https://cloud.google.com/run/docs/logging#writing_structured_logs) for writing structured logs, but nothing shows in the Cloud Logging Explorer.

Did something change and the docs are no longer up-to-date? Any idea what could I be doing wrong?
Is the stdout logging no longer supported and that's why you are using **google.cloud.logging** library?

Thanks a lot!

**Comment by meseta** [comment]
are we getting structured logging!? woohoo!

**Comment by lorenzznerol** [comment]
> I tried to implement @Voyz solution on a Cloud Function and I couldn't make it work. I think there is a strange behaviour with CF and monkey patching the module.
> 
> ```python
> def my_enqueue(
>     self, record, message, resource=None, labels=None, trace=None, span_id=None
> ):
>     queue_entry = {
>         "info": {
>             "message": message,
>             "python_logger": record.name,
>             "error_fields": record.error_fields,
>         },
>         "severity": _helpers._normalize_severity(record.levelno),
>         "resource": resource,
>         "labels": labels,
>         "trace": trace,
>         "span_id": span_id,
>         "timestamp": datetime.datetime.utcfromtimestamp(record.created),
>     }
>     self._queue.put_nowait(queue_entry)
> 
> 
> _Worker.enqueue = my_enqueue
> ```
> 
> And the function...
> 
> ```python
> def index(request):
>     logger = logging.getLogger("my_log_client")
>     handler = CloudLoggingHandler(
>         logger_client, name="my_log_client", transport=BackgroundThreadTransport
>     )
>     logger.setLevel(logging.INFO)
>     logger.addHandler(handler)
>     logging.info("hello")
>     logging.info("hello", extra={"custom_one": 1})
>     logger.info("hello", extra={"error_fields": {"foo": 1, "bar": {"tzar": 3}}})
>     return ("", 202)
> ```
> 
> I would expect some error if `logging.info("hello")` does not have the `error_fields` keys. Is there any update if this will be implemented?
> 
> ![image](https://user-images.githubusercontent.com/29377393/79504314-b861e480-8000-11ea-97da-9ad06a856b97.png) No errors :(

This question here is not for a cloud function, there, you have to use google.cloud.logging instead of the stdlib Python logging. 

This question here is just about getting it to work in a local Python script, using the GOOGLE_APPLICATION_CREDENTIALS to connect to GCP and drop the logs there.
