### ISSUE TITLE
API differences between HTTP and gRPC implementations

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-logging#154]
We have two methods of interacting with the API backend: gRPC (default) and HTTP (used when client is created with `google.cloud.logging.Client(_use_grpc=0)` or `DISABLE_GRPC` is set).

This is implemented using two _*API implementations: One in [_http.py](https://github.com/googleapis/python-logging/blob/ff90fd2fb54c612fe6ab29708a2d5d984f60dea7/google/cloud/logging_v2/_http.py) and the other in [_gapic.py](https://github.com/googleapis/python-logging/blob/master/google/cloud/logging_v2/_gapic.py). It looks like in some cases, they return different values (_http returns a page iterator object directly, while _gapic often converts it to a generator. This confuses users who expect high-level APIs to act consistently regardless of the implementation used.

I suggest we refactor _http.py to be consistent with _gapic.py, and add tests to make sure they act consistently

**Comment by busunkim96** [comment]
FYI @Daniel-Sanche, there is work underway for GAPIC to have a fallback http transport. See [doc](https://docs.google.com/document/d/1u0WGcF6woB9HnyUK5J-GaBCRUc9G4znwbvcB4QdYq8s/edit#). It should eventually be possible to remove the handwritten HTTP implementation and just maintain the wrapper around GAPIC.

**Comment by daniel-sanche** [comment]
Good to know. For the v3 release, we should make sure the APIs are compatible, but we should avoid investing too much time in the hand-written code and plan to use the gapic code instead
