### ISSUE TITLE
Allowing filtering/formatting of Stackdriver logs

### ISSUE THREAD

**Issue by joshburkart** [googleapis/python-logging#17]
Hello,

I'm using the [instructions here](https://googlecloudplatform.github.io/google-cloud-python/latest/logging/usage.html#integration-with-python-logging-module) to send Python `logging` module logs to Stackdriver. Thanks for making this so easy! However, doing this naively seems to make all logs from potentially many jobs/VMs/etc. get merged together in the Stackdriver UI. When I filter to e.g. a specific VM, none of the logs show up ([screenshot](https://snag.gy/dNU6hj.jpg)) -- I have to set the filtering to "Global" to see them ([screenshot](https://snag.gy/ARyEc8.jpg)). Am I doing something wrong?

Also, what about logging things like files, line numbers, etc.? Is this possible? Does Stackdriver respect [formatting I apply](https://docs.python.org/3/library/logging.html#formatter-objects) using the Python logging API? What about automatic links to files in connected code repos etc. -- any info available on that?

Thanks!

**Comment by Daniel-Sanche** [comment]
As of https://github.com/googleapis/python-logging/pull/200, the resource should be auto-detected for each GCP environment. It sounds like that was the ask for this issue, so I'll close this. Feel free to re-open if there are any remaining concerns
