### ISSUE TITLE
log_struct severity isn't captured as expected

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-logging#190]
## What is the issue: 
On using Python client library for Cloud Logging, log_struct is used to send structured logs to Cloud Logging. In structured logging, the log message and metadata are stored in Python dictionary and it is passed to the 1st argument of the method. However, the severity field is not handled as expected because severity needs to be assigned as named argument, which is not explicit from the library document.

## Link to friction log: 
https://docs.google.com/document/d/19Glb2LC1jXyARXLlJbdRjY1d7I2GolCntI5hck5PuGU/edit?usp=sharing

## How bad is it on a scale of 1-5 (1=Minor Annoyance; 5=Total Work Blocker)

4

## What were you trying to do?

This issue was originally reported by the customer (TV Asahi), and I reproduced it.

I tried to send structured logs to Cloud Logging with its Python client library.

##What did you expect to happen?

The 1st argument of log_struct accept the dictionary with whole metadata valid for LogEntry and handle the log severity stored in that dictionary.

That is, expecting this code:
```
logdata = {
    "service": service,
    "message": message,
    "messageId": context.event_id,
    "timepublished": context.timestamp,
    "severity": "warning"
}

vplogger.log_struct(logdata)
```
is treated as WARNING level log in Cloud Logging.

## What actually happened?

It was treated as DEBUG level log.

**Comment by ecotner** [comment]
hey, I'm not sure if this is 100% correct, but my understanding is that the first argument to `log_struct` is supposed to be the JSON payload itself; you're supposed to add metadata as additional kwargs, e.g. you could do something like
```python
vplogger.log_struct(logdata, severity="WARNING")
```
or
```python
vplogger.log_struct(logdata, severity=logdata["severity"])
```
this is what I do to specify the log severity, and it works for me

**Comment by Daniel-Sanche** [comment]
Thanks, that was how I thought it might work. I think it would be more friendly if the library would extract the severity from the JSON if it's not passed as a parameter. But this seems like an API-breaking change, so it will have to wait for the next major release
