### ISSUE TITLE
[Enhancement] Make ensure_ascii adjustable in ContainerEngineHandler

### ISSUE THREAD

**Issue by ysde** [googleapis/python-logging#192]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
Allow unicodes to show in log instead of ascii character (for example, show chinese word '哈' in log instead of something like  '\u8bed')

 **Describe the solution you'd like**
Add a constructor parameter `json_ensure_ascii` in `class ContainerEngineHandler`  and add a parameter `json_ensure_ascii` in `def format_stackdriver_json`

 **Describe alternatives you've considered**
Currently no...

 **Additional context**
Nope

**Comment by daniel-sanche** [comment]
Unicode support was added in https://github.com/googleapis/python-logging/pull/193, with more environment tests added in https://github.com/googleapis/python-logging/pull/267
