### ISSUE TITLE
how to increase _DEFAULT_GRACE_PERIOD=5 sec 

### ISSUE THREAD

**Issue by jawlitkp** [googleapis/python-logging#3]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hello, 

Is there any way I can change _DEFAULT_GRACE_PERIOD. I am getting the below error.

Program shutting down, attempting to send 4433 queued log entries to Stackdriver Logging...
Waiting up to 5 seconds.
Failed to send 3434 pending logs.

**Comment by Daniel-Sanche** [comment]
Sorry for the slow response. BackgroundTransport objects take in a [grace_period](https://github.com/googleapis/python-logging/blob/92b287f424418fde137cc81f370dcab07f84023b/google/cloud/logging_v2/handlers/transports/background_thread.py#L255) argument that you can set at initialization. If you create a custom BackgroundTransport object, you can then [pass it in to any handler object](https://github.com/googleapis/python-logging/blob/92b287f424418fde137cc81f370dcab07f84023b/google/cloud/logging_v2/handlers/handlers.py#L61)
