### ISSUE TITLE
StructuredLogHandler breaks when args in LogRecord

### ISSUE THREAD

**Issue by kwsz** [googleapis/python-logging#313]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-logging/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: linux
  - Python version: 3.9
  - pip version:
  - `google-cloud-logging` version: 2.4.0

#### Steps to reproduce

  1. run the code
  2. only shows 'Name: %s' in the message field

#### Code example

```python
handler = StructuredLogHandler()
setup_logging(handler)
name = "Amy"
logging.info('Name: %s', name)
```

#### Suggestions
I think GCP_FORMAT["message"] should be "%(message)s"

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by daniel-sanche** [comment]
Thanks for raising this, it is fixed in https://github.com/googleapis/python-logging/pull/319 and will be released with v2.5.0 next week
