### ISSUE TITLE
Need to clean up Pub/Sub topic resources during tests

### ISSUE THREAD

**Issue by anguillanneuf** [googleapis/python-logging#323]
Using this issue to track [how many](https://pantheon.corp.google.com/cloudpubsub/topic/list?project=python-docs-samples-tests&pageState=(%22cpsTopicList%22:(%22f%22:%22%255B%257B_22k_22_3A_22Topic%2520name_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22sink-pubsub_5C_22_22_2C_22i_22_3A_22name_22%257D%255D%22))) topics are created but  not cleaned up by the samples tests in 

https://github.com/googleapis/python-logging/blob/bce67419df6ad82d3d6d87957b47c6d4f02be1cf/samples/snippets/usage_guide.py#L253

Note that there's a hard limit of 10,000 Pub/Sub topics per project.

**Comment by daniel-sanche** [comment]
Good catch, I opened https://github.com/googleapis/python-logging/pull/324 to address this. Let me know if you see any other resources that aren't being cleaned up properly
