### ISSUE TITLE
structured logging fails to create valid json in some cases

### ISSUE THREAD

**Issue by EricLacherSolera** [googleapis/python-logging#331]
I think I found a bug in v3.0.0 branch, causing invalid json being generated, thus having no jsonPayload in GCP Logging and instead receiving a textMessage.

#### Environment details

  - code deployed on GCP Cloud Run
  - using library version from v3.0.0 branch
 
#### Steps to reproduce

1. use structured logging according to examples
2. log any dict with double ending braces ( '{ "x": { "y" : "z" }}')
3. see https://github.com/googleapis/python-logging/blob/3d03805ff9ab7cdf16c41f67a7453b2d8f5c70ce/google/cloud/logging_v2/handlers/structured_log.py#L69 using lstrip and rstrip, causing removal of both braces at the end
4. receive textMessage instead of jsonPayload in GCP Logging, as invalid json was produced.

#### Possible fix

I am not a python programmer, so you might find better solutions, however, this is what worked for me:
```
if isinstance(record.msg, collections.abc.Mapping):
    encoded_msg = json.dumps(record.msg, ensure_ascii=False)
    payload_clean = encoded_msg.lstrip().rstrip() // remove whitespace
    # strip out open and close parentheses
    if payload_clean.startswith("{"):
        payload_clean = payload_clean[1:] // strip leftmost character
    if payload_clean.endswith("}"):
        payload_clean = payload_clean[:-1] // strip rightmost character
    payload = payload_clean + ","
```

Thanks a lot for bringing structured (json) logging into the lib!

**Comment by daniel-sanche** [comment]
Thanks for bringing this up, I added support for string-encoded dictionaries in https://github.com/googleapis/python-logging/pull/339

FYI, the v3.0.0 branch is a WIP so may not always be fully bug-free before release, but I appreciate the early feedback!
