### ISSUE TITLE
log_text hangs inside apache but works inside shell

### ISSUE THREAD

**Issue by bhaskar8088** [googleapis/python-logging#34]
Hello,

I am trying to log_text using environmental variable kind of authentication.

Its working in shell but hangs when ran using flask, apache2.

I tried with both v1 and v2 but same result with both. Any thoughts? Assuming it doesnt work, may be its better I use direct apis rather than this python sdk?

Thanks

**Comment by busunkim96** [comment]
Are you providing service account credentials in those environments? https://cloud.google.com/logging/docs/setup/python

**Comment by bhaskar8088** [comment]
I am providing like below
 export GOOGLE_APPLICATION_CREDENTIALS=path_to_json.json

Anyway, this might not have worked for me. But the python google login handler worked for me, so using that. Thanks.
