### ISSUE TITLE
Logs not bundling with request

### ISSUE THREAD

**Issue by jacobg** [googleapis/python-logging#361]
#### Environment details

  - OS type and version:  Mac OS 11.5
  - Python version: 3.9
  - pip version: 21.0.1
  - `google-cloud-logging` version: 2.5.0

#### Steps to reproduce

Run simple python script that submits a couple app log entries followed by a request log entry.

Expected behavior:  App log entries bundled under request log, similar to this screenshot (albeit a bit dated):

<img width="954" alt="3IJMv" src="https://user-images.githubusercontent.com/736985/127048724-3f5be76b-6257-4428-aaa8-e25286250e9a.png">

Actual behavior: All log entries are separate, as shown in this screenshot:

<img width="987" alt="Screen Shot 2021-07-26 at 3 29 44 PM" src="https://user-images.githubusercontent.com/736985/127048543-f1b22df4-28e9-45b8-a30d-c803b35d4444.png">

#### Code example

```python
import argparse
import datetime
import time
import uuid

from google.cloud import logging


def _log_timestamp():
    return datetime.datetime.now(datetime.timezone.utc)


def _log_trace_id():
    return uuid.uuid4().hex


def _log_request_time(request_start_time):
    return "%.5fs" % (time.time() - request_start_time)


def run(project_id):
    request_start_time = time.time()
    trace_id = _log_trace_id()

    client = logging.Client(project=project_id)

    app_logger = client.logger('child')
    app_logger.log_struct(
        {"message": 'app log entry # 1'},
        severity='INFO',
        trace=f'projects/{project_id}/traces/{trace_id}',
        timestamp=_log_timestamp()
    )
    app_logger.log_struct(
        {"message": 'app log entry # 2'},
        severity='INFO',
        trace=f'projects/{project_id}/traces/{trace_id}',
        timestamp=_log_timestamp()
    )

    request_logger = client.logger('parent')
    request_logger.log_struct(
        {"message": 'TEXT'},
        severity='INFO',
        trace=f'projects/{project_id}/traces/{trace_id}',
        timestamp=_log_timestamp(),
        http_request=dict(
            request_method='GET',
            request_url='https://request.example.com/test-logging',
            status=200,
            user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko)'
                       ' Chrome/92.0.4515.107 Safari/537.36',
            response_size=15773,
            latency=_log_request_time(request_start_time),
            remote_ip='127.0.0.1',
            referer='https://referer.example.com/',
        )
    )


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument('--project',
                        required=True,
                        help='Project ID')
    args = parser.parse_args()

    run(args.project)

```

**Comment by daniel-sanche** [comment]
Hey jacobg,

Unfortunately, this is out of scope of the client libraries. This library is responsible for sending logs to the backend, but isn't responsible for how the logs are displayed in the GCP Cloud Console.

My understanding is that request log grouping is only available on App Engine, but I'd recommend opening an issue on the official [Cloud Logging tracker here.](https://cloud.google.com/support/docs/issue-trackers)

**Comment by jacobg** [comment]
Google Cloud Support was able to find an answer, and it's working for me now. It is available outside of App Engine. The problem was not in the library. There's a seemingly undocumented "gotcha" in the Log Viewer in order to see the logs bundled by request, and that is that the log query needs to filter specifically for the request parent's logName. Then the child log's will be nested underneath it. If you don't filter for logName, then they all the request and app log entries are displayed in a flat list. That is a quirky difference from App Engine, which seems to abstract over log names, perhaps by ingesting it differently.

**Comment by daniel-sanche** [comment]
Great, thanks for coming back to provide the solution!
