### ISSUE TITLE
StructuredLogHandler appends Traceback

### ISSUE THREAD

**Issue by tombeck** [googleapis/python-logging#382]
The StructuredLogHandler appends a Traceback after the json structured log message.
This causes a second unstructured log entry with just the traceback when the handler is used in a Google Cloud Function.

#### Code example

```python
import logging

from google.cloud.logging.handlers import StructuredLogHandler

logger = logging.getLogger()
logger.handlers.clear()
logger.addHandler(StructuredLogHandler())

try:
    raise Exception("Test")
except Exception:
    logger.exception("Failed")
```

#### Output
```
{"message": "Failed\nTraceback (most recent call last):\n  File \"main.py\", line 10, in <module>\n    raise Exception(\"Test\")\nException: Test", "severity": "ERROR", "logging.googleapis.com/labels": {}, "logging.googleapis.com/trace": "", "logging.googleapis.com/spanId": "", "logging.googleapis.com/sourceLocation": {"line": 12, "file": "main.py", "function": "<module>"}, "httpRequest": {} }
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    raise Exception("Test")
Exception: Test
```

The traceback appears twice. Once inside the structured log message and again after it. This happens because a logging.Formatter is used which always appends the traceback if exc_info or exc_text is present.

**Comment by daniel-sanche** [comment]
Thanks for reporting this, the duplicate entry has been fixed. After the next release, you should see a single log entry with the message and traceback, in line with python logging stdlib expectations
