### ISSUE TITLE
docs: validate django/flask versions

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-logging#429]
We rely on django and flask to find http_request data from incoming requests. It seems like the tests all target [the latest version](https://github.com/googleapis/python-logging/blob/76ac729e42a782524be87ad71745aad37bbe1653/noxfile.py#L98). We should make sure we test multiple versions, and document which ones are supported in the usage guide

**Comment by Zaidtech** [comment]
Hello @daniel-sanche,
Is this issue still open? Can I work upon it?

**Comment by Zaidtech** [comment]
Yeah!
Do I need to set up a google cloud project before making progress in this issue?
