### ISSUE TITLE
Missing labels

### ISSUE THREAD

**Issue by jamborta** [googleapis/python-logging#433]
#### Environment details

  - OS type and version: Debian GNU/Linux 11 (bullseye)
  - Python version: 3.7.12
  - `google-cloud-logging` version: 2.6.0

#### Steps to reproduce

I'm running this pod on Kubernetes that frequently sends logs with missing labels. About 50% of the logs that are sent have missing labels.

Here is an example:

```json
{
  "insertId": "wpogfddrynbxrlyk",
  "jsonPayload": {
    "message": "",
    "thread": 140001363777344
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "cluster_name": "",
      "container_name": "main",
      "pod_name": "pod1",
      "location": "europe-west4-c",
      "project_id": "",
      "namespace_name": ""
    }
  },
  "timestamp": "2021-10-27T09:00:27.006503105Z",
  "severity": "INFO",
  "labels": {
    "k8s-pod/statefulset_kubernetes_io/pod-name": "pod1",
    "compute.googleapis.com/resource_name": "pool-name",
    "k8s-pod/app": "app-name",
    "k8s-pod/controller-revision-hash": "",
    "k8s-pod/market": ""
  },
  "logName": "projects/project-id/logs/stderr",
  "receiveTimestamp": "2021-10-27T09:00:31.253470430Z"
}
```

straight after that, this entry has most of the labels missing:

```json
{
  "insertId": "8bz8rf4vy1wxqf3w",
  "jsonPayload": {
    "thread": 140001363777344,
    "message": ""
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "location": "europe-west4-c",
      "project_id": "",
      "namespace_name": "",
      "container_name": "main",
      "cluster_name": "",
      "pod_name": "pod1"
    }
  },
  "timestamp": "2021-10-27T09:00:32.374535322Z",
  "severity": "INFO",
  "labels": {
    "compute.googleapis.com/resource_name": "pool-name"
  },
  "logName": "projects/project-id/logs/stderr",
  "receiveTimestamp": "2021-10-27T09:00:36.551728409Z"
}
```

**Comment by daniel-sanche** [comment]
This issue would be out of scope of the logging library. The library writes [structured JSON logs](https://cloud.google.com/logging/docs/structured-logging#special-payload-fields) to standard out on GKE environments, which are then parsed by the GKE logging agent and sent into GCP. These GKE-specific labels are added by the agent, downstream of this library code.

I'd suggest reaching out to [GKE support](https://cloud.google.com/kubernetes-engine/docs/getting-support) for help with the logging agent outputs. Thanks
