### ISSUE TITLE
Silent failures retrieving stackdriver logs

### ISSUE THREAD

**Issue by smfritzii** [googleapis/python-logging#54]
Sometimes log filters return no results when results are expected. 
#### Environment details

  - OS type and version: Fedora 31 5.6.18-200.fc31.x86_64
  - Python version: `python --version` Python 3.7.7
  - pip version: `pip --version` pip 19.1.1
  - `google-cloud-logging` version: `pip show google-cloud-logging`
Name: google-cloud-logging
Version: 1.15.0
Summary: Stackdriver Logging API client library
Home-page: https://github.com/googleapis/python-logging
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
#### Steps to reproduce

  1. Submit a filter to stackdriver, which you expect to return results
  2. Sometimes it returns an iterator with 50 pages (the expected behavior), sometimes an iterator with 1 page of 0 results.

#### Code example
```python
from google.cloud import logging
from google.cloud.logging import DESCENDING
from google.cloud.logging import ASCENDING
...
        self.client = logging.Client(project = myProject)
        stackDriverLog = self.client.logger(logName)
        logFilter='"<your text value>"' #I am searching for an internal ID string with hex-like values, ie 'ab12cd34'
        iterator=stackDriverLog.list_entries(order_by=ASCENDING,filter_=logFilter)
        pages=iterator.pages
        page=next(pages)
```

**Comment by Daniel-Sanche** [comment]
I haven't been able to reproduce this. We made some changes around the filter code in the last few months, and this is an old bug, so I'm going to close it. If you're still seeing the issue, feel free to re-open and we can debug together (I'd be interested if you're able to see the logs on gcloud, but not through the library with the same filter)
