### ISSUE TITLE
Severity concatenation when setting metadata severity

### ISSUE THREAD

**Issue by averikitsch** [googleapis/python-logging#543]
When specifying both severity as extra JSON payload and using the python std lib severity, results in a concatenation of values in Cloud Logging.

![Screen Shot 2022-05-02 at 1 05 34 PM](https://user-images.githubusercontent.com/6519888/166318398-f94b2f9f-ad7f-4818-9608-69bbe3694e2e.png)

#### Environment details

  - OS type and version: Functions Gen 2
  - Python version: 3.8
  - `google-cloud-logging` version: 3.0.0

#### Steps to reproduce

  1. Set `"severity":"error"` in metadata
  2. Use `logger.info` to write log
  3. See combination of both severity types instead of selecting one or another.

#### Code example

```python
import functions_framework
from google.cloud.logging import Client


@functions_framework.http
def structured_logging(request):
    logging_client = Client()
    logging_client.setup_logging()
    import logging
    msg = "Hello, world!"

   # Important snippet below
    metadata = {"component": "arbitrary-property", "severity":"error"}
    logging.info(msg, extra={"json_fields": metadata})

    return "Success: A log message was written"
```

**Comment by daniel-sanche** [comment]
**Cause**
It looks like like the StructuredLogHandler will output JSON like this for your log:

```
{ "severity": "INFO", "message" "Hello World", "severity" "error", "component": "arbitrary-property" }
```

The Cloud Run logging agent will attempt to parse out the severity from the JSON, and it looks like it concatenates the data together if there are duplicate severity fields.

**Solution**
I think the right fix to this would be to delete [reserved name fields](https://cloud.google.com/logging/docs/structured-logging) like severity out of the `json_fields` dictionary when using `StructuredLogHandler`. We could consider adding a prefix to any special fields in the json payload so they still show up in the payload without confusing the agents, but I think that would cause more confusion and trouble than it's worth

Let me know if you have thoughts
