### ISSUE TITLE
What I specify as labels is output as logging.googleapis.com/labels

### ISSUE THREAD

**Issue by cuzkop** [googleapis/python-logging#552]
# description

I use custom labels because I want to keep track of whether the error should be notified or not with a label.
I am having trouble with different output depending on how python is written.
I don't know how I understand.

# Environment details

  - cloud functions
  - Python3.8
  - google-cloud-logging==3.0.0

# Code example

It output to labels.

```python
client = google.cloud.logging.Client()
client.setup_logging()

logging.error("message", extra={
    "json_fields": {"status": "ng"},
    "labels": {"slack_notify": "true"}
})
```

It output to `logging.googleapis.com/labels` in jsonPayload

```python
client = google.cloud.logging.Client()
client.setup_logging()

logging.error("message", extra={
    "json_fields": {"status": "ng"},
    "labels": {"slack_notify":  True}
})
```

**Comment by cuzkop** [comment]
Hello @arbrown , I'm reporter.
Any progress on this issue?

**Comment by minherz** [comment]
hi, we will look into it to see whether it is a bug or not. is there a particular reason why you choose to print the logs to stdout instead of ingesting it directly to Cloud Logging?

**Comment by cuzkop** [comment]
hi @minherz , thanks for your help.
Actually, we have no particular reason but [google-cloud-logging docs](https://googleapis.dev/python/logging/latest/std-lib-integration.html) recommended to integrate python standard library and cloud logging library, so we choose it.

**Comment by cuzkop** [comment]
@daniel-sanche 
Thank you!
I understand that condition and we use string.

**Comment by minherz** [comment]
Closing the issue as inactive. Feel free to reopen if the question is still relevant.
