### ISSUE TITLE
Add support for typing

### ISSUE THREAD

**Issue by yaronbenezra** [googleapis/python-logging#573]
Hi,
when you will support python 3.9?

Regards,
Yaron

**Comment by bissli82** [comment]
> Hi there @bissli82 - We do run tests against python 3.9 and don't see any issues. You should be able to use it, are you seeing some specific issue preventing you from using the library with python 3.9?

Hi, yes we're having issue with typing - type hints(added if I recall on 3.8+), I'll try and recreate it and upload it here

**Comment by meredithslota** [comment]
The README does not specify 3.9 support (yet) — could this be added there? (And I think a recent PR just dropped 3.6, too.)

**Comment by daniel-sanche** [comment]
I believe Python3.9 should be supported with no issues now. Feel free to re-open if you still have a problem with typing
