### ISSUE TITLE
Fix Autogenerated Samples

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/python-logging#582]
The log tailing samples ([synchronous](https://github.com/googleapis/python-logging/blob/main/samples/generated_samples/logging_v2_generated_logging_service_v2_tail_log_entries_sync.py), [asynchronous](https://github.com/googleapis/python-logging/blob/main/samples/generated_samples/logging_v2_generated_logging_service_v2_tail_log_entries_async.py)) have an issue where the object paths are out of date (`logging_v2.LoggingServiceV2Client()` should be `logging_v2.services.logging_service_v2.LoggingServiceV2Client()`, etc)

We should check the autogenerated samples to make sure they are all tested

**Comment by dlobsinger** [comment]
Is there any update on a working sample of using `tail_log_entries`?
