### ISSUE TITLE
ContainerEngineHandler: Set tracing information in JSON message if available in LogRecord

### ISSUE THREAD

**Issue by AmicoJoules** [googleapis/python-logging#63]
The current implementation of `ContainerEngineHandler` is only filling `message`, `timestamp`, `thread` and `severity` of the fluentd JSON string (see https://github.com/googleapis/python-logging/blob/c4387b307f8f3502fb53ae1f7e1144f6284280a4/google/cloud/logging/handlers/_helpers.py#L41), so any tracing information contained in the LogRecord is lost and cannot be visualized in StackDriver.

My first proposal would be to change the implementation of `format_stackdriver_json` to check if the LogRecord has the tracing attributes, the names would be based on the official [Trace integration with cloud logging guide](https://cloud.google.com/trace/docs/trace-log-integration) (`trace`, `span_id` and `trace_sampled`) so it would look similar to this:

```
def format_stackdriver_json(record, message):
    """Helper to format a LogRecord in in Stackdriver fluentd format.

        :rtype: str
        :returns: JSON str to be written to the log file.
    """
    subsecond, second = math.modf(record.created)

    payload = {
        "message": message,
        "timestamp": {"seconds": int(second), "nanos": int(subsecond * 1e9)},
        "thread": record.thread,
        "severity": record.levelname,
    }

    if hasattr(record, 'trace'):
        payload["logging.googleapis.com/trace"] = record.trace

   if hasattr(record, 'span_id'):
        payload["logging.googleapis.com/spanId"] = record.span_id

    if hasattr(record, 'trace'):
        payload["logging.googleapis.com/trace_sampled"] = record.trace_sampled

    return json.dumps(payload)

```

Another option would be to allow passing an optional formatter function in the class constructor and call it if it was provided otherwise just use the current function.

If you agree with any of this options I'm happy to submit a PR

**Comment by Daniel-Sanche** [comment]
Thanks for the suggestion, I'm going to look into how feasible this change is

**Comment by daniel-sanche** [comment]
As of v2.4.0, trace and span info will be captured in the LogEntry as part of the [CloudLoggingFilter class](https://github.com/googleapis/python-logging/blob/00d1c37380780f2c72cb8986cf6cbae7d650999a/google/cloud/logging_v2/handlers/handlers.py#L39). The CloudLoggingHandler and StructuredLogHandler classes will then use that information as part of the log sent to Cloud Logging
