### ISSUE TITLE
RequestMiddleware not working at Django 4.1

### ISSUE THREAD

**Issue by tokibito** [googleapis/python-logging#677]
I tryed to use `google.cloud.logging_v2.handlers.middleware.RequestMiddleware` at Django 4.1.3, Python 3.10 but errors raises bellow:

#### Environment details

  - OS type and version: Linux
  - Python version: `3.10`
  - pip version: `pip-22.3.1`
  - `google-cloud-logging` version: `3.2.5`

#### Steps to reproduce

  1. Create new Django project.
  2. Add the `RequestMiddleware` to settings.MIDDLEWARE
  3. start runserver
  4. access `/` path  --> error raised.

#### Code example

```python
# settings.py at Django
MIDDLEWARE = [
    'google.cloud.logging_v2.handlers.middleware.RequestMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
```

#### Stack trace
```
Traceback (most recent call last):
  File "/home/vagrant/tmp/myproject/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/vagrant/tmp/myproject/venv/lib/python3.10/site-packages/django/utils/deprecation.py", line 131, in __call__
    if self._is_coroutine:
AttributeError: 'RequestMiddleware' object has no attribute '_is_coroutine'
```

At the same code, when using Django 4.0.8, it's working.

**Comment by daniel-sanche** [comment]
This should be fixed by [this recent PR](https://github.com/googleapis/python-logging/issues/625), which will soon be [released as v3.3.0](https://github.com/googleapis/python-logging/pull/645)

I just did a quick test with Django 4.1.3, and didn't run into any issues. Please re-open it if you still have problems after the 3.3.0 release
