### ISSUE TITLE
Mention query time and optimization when using list_entries in the docs

### ISSUE THREAD

**Issue by Mapiarz** [googleapis/python-logging#68]
Hi.

The library docs explain how to retrieve and query for logs using `list_entries` methods, simple enough. Nonetheless, I was quite puzzled today as to why my queries, even though very simple, take minutes to get the response from the API. After quite a lot of googling and digging deep into Logging docs, I was able to find an answer: https://cloud.google.com/logging/docs/view/advanced-queries#finding-quickly

The reason why my queries took so long to execute is because I didn't limit the time period of my queries. This can be very confusing for newcomers and I think the docs could use a paragraph about query time and that most queries should be limited by time period (like they are, for instance, in the Google Cloud Platform web logs browser) or that if not limited by time period they can take a lot of time to execute.

Regards,
Bartosz

**Comment by Daniel-Sanche** [comment]
I'm going to close this because https://github.com/googleapis/python-logging/pull/73 removes the root issue (long queries without time bounds). I'll re-evaluate the docs later to see if we can improve things there as well
