### ISSUE TITLE
Django server errors are not grouped with the request log

### ISSUE THREAD

**Issue by clement-escolano** [googleapis/python-logging#716]
#### Environment details

  - OS type and version: Docker
  - Python version: `3.10`
  - pip version: `22.3.1`
  - `google-cloud-logging` version: `3.3.1`

#### Steps to reproduce

  1. Configure `google-cloud-logging` for a Django project so that regular logs are grouped in the logging panel
  2. Trigger an internal server error (`raise "Error"`) in an endpoint
  3. Call the endpoint

#### Code example

`google-cloud-logging` is configured like this in our Django settings

```python
client = Client()
handler = handlers.CloudLoggingHandler(client)
handlers.setup_logging(handler)
MIDDLEWARE = [
    "google.cloud.logging_v2.handlers.middleware.request.RequestMiddleware"
] + MIDDLEWARE
```

#### Logs not grouped in the logging panel

<img width="1138" alt="Capture d’écran 2023-01-27 à 11 51 28" src="https://user-images.githubusercontent.com/11637509/215070151-fb7ba906-ef71-4981-941b-efc111728363.png">

**Comment by daniel-sanche** [comment]
Thanks for reporting this. Could you share the full log data, for both a log that is grouped and one that is not grouped?

**Comment by clement-escolano** [comment]
What do you mean "the full log data"?
Here is another screenshot for the "grouped" logs:
<img width="1055" alt="Capture d’écran 2023-02-01 à 11 03 20" src="https://user-images.githubusercontent.com/11637509/216012834-856b2a99-5103-4ecb-b574-7247c782525b.png">

**Comment by daniel-sanche** [comment]
I'm looking for something like that screenshot, but with the httpRequest field expanded. And I'm also curious what the non-grouped log looks like fully expanded. 

Some of the logic behind the grouping is [described here](https://github.com/googleapis/google-cloud-go/blob/112bcdeb7cee1b44f337d3e5398a0d0820e93162/logging/doc.go#L116). It's based on data stored in the trace and httpRequest fields, so it would be helpful to see what data you're seeing on your end to tell what may be going on

**Comment by clement-escolano** [comment]
<img width="379" alt="Capture d’écran 2023-02-15 à 12 26 38" src="https://user-images.githubusercontent.com/11637509/219015826-0f61127d-e12c-4427-847a-7b36f8622725.png">
This is the screenshot for the 500 error. The request log is correctly mapped (HTTP status, browser, there is the trace) but the log above (which is the traceback of the actual error) does not have relevant informations.
Below is the content of the log that is correctly grouped with the request (which is the same by the way).
<img width="971" alt="Capture d’écran 2023-02-15 à 12 32 51" src="https://user-images.githubusercontent.com/11637509/219016514-96c0bb3e-7bd5-4c9c-b972-e7bba96a9519.png">

**Comment by daniel-sanche** [comment]
So it looks like the error you are interested in is being captured through standard error on Cloud Run. Cloud Run will automatically capture any stdout/stderr messages and send them to Cloud Logging as a platform feature, outside the scope of this library. Unfortunately we can't really do anything about this at the library level

One thing you could do is have a try/catch block that captures the exception, and then explicitly log the traceback using a logger object. That way, the error log will go through the GCP logging library, and should contain the expected regular trace and http fields

You can also file this as a bug on the Cloud Run team, and they may have suggestions or a fix to have the standard Cloud Run stderr logs capture trace and request data

**Comment by clement-escolano** [comment]
OK understood. I tried adding a middleware with a try/catch and the logs passes through the logging library (I know it because I added another middleware to add information to the logs in GCP and they indeed appear) but the trace is not present so the error log is still not grouped.

Here is the middleware code:

```py
def LogExceptionsMiddleware(get_response):
    def middleware(request):
        if get_response:
            try:
                return get_response(request)
            except Exception as e:
                logging.getLogger("django").exception("TEST")
                raise e
        else:
            return None

    return middleware
```

Anyway, I think I will just use timestamps to retrieve the error logs for a request for now.
Thank you for your help and your time
