### ISSUE TITLE
DeprecationWarning for pkg_resources.declare_namespace("google.logging")

### ISSUE THREAD

**Issue by skshetry** [googleapis/python-logging#730]
Starting from `setuptools==67.3.0`, it has started raising DeprecationWarning. Some libraries treat them as errors during testing.

See: https://setuptools.pypa.io/en/latest/history.html#v67-3-0.

```python
/lib/python3.11/site-packages/pkg_resources/__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google.logging')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)
```

See similar discussion in https://github.com/matplotlib/matplotlib/issues/25244 and https://github.com/pypa/setuptools/pull/3434#issuecomment-1435697632. 

Also opened a similar issue in `google.cloud`: https://github.com/googleapis/python-storage/issues/1000.

**Comment by meredithslota** [comment]
Thanks for filing this — this is the broader issue for the whole set of Python libraries, we will be working on dropping `pkg_resources` at more or less the same time across all of them: https://github.com/googleapis/google-cloud-python/issues/11184
