### ISSUE TITLE
Logging not working inside of a scheduler job

### ISSUE THREAD

**Issue by space192** [googleapis/python-logging#748]
We are trying to log to the journal of a cloud scheduler job, but nothing appears other than prints, but it works in regular cloud runs.

#### Environment details

  - Docker python3.9:slim
  - pip version: 23.1.2
  - `google-cloud-logging` version: 3.5

#### Steps to reproduce

  1. Try to use Logging inside of a cloud scheduler job
  2. use the code snippet provided as an example for logging text or struct

#### Code example

```python
def write_entry(logger_name):
    logging_client = logging.Client()
    logger = logging_client.logger(logger_name)
    logger.log_text("Hello, world!")
    logger.log_struct(
        {
            "name": "King Arthur",
            "quest": "Find the Holy Grail",
            "favorite_color": "Blue",
        }
    )
```

**Comment by daniel-sanche** [comment]
Where are you looking for the logs to appear? Note that logs likely won't appear in the Cloud Scheduler UI without proper metadata linking it to a scheduler job, but you may be able to see them in the unfiltered stream on the [Cloud Logging dashboard](https://console.cloud.google.com/logs).

Also, I'm not too familiar with the Cloud Scheduler backend, but if it supports stdout log capture, you can try using the [StructuredLogHandler integration](https://cloud.google.com/python/docs/reference/logging/latest/std-lib-integration#manual-handler-configuration), which will write formatted logs over stdout. This avoids network calls, and is most reliable on environments that support it

**Comment by daniel-sanche** [comment]
Ok so to make sure I understand: 
- When using this library's `logger.log_text` and `logger.log_struct`, no logs are appearing in Cloud Logging
- When printing to stdout, logs show up as textpayloads, even when following [structured logging JSON formatting](https://cloud.google.com/logging/docs/structured-logging#special-payload-fields)
- When using StructuredLogHandler, you see the same results as printing to stdout, meaning just textpayloads with no structure

Is that correct?

**Comment by space192** [comment]
- no logs appear in cloud logging for cloud scheduler jobs
- they always show up as text payload
- and the last one doesn't even show up on the cloud scheduler jobs

**Comment by space192** [comment]
Just checked again and with StructuredLogHandler, it prints out that all pending logs have been sent, but the json payload still doesn't appear anywhere

**Comment by daniel-sanche** [comment]
Hmm can you share a code snippet of how you're using the StructuredLogHandler? It should be printing directly to stdout hen configured properly, so you shouldn't see anything about pending logs.

That said, (assuming this point is true: `"they always show up as text payload"`), the StructuredLogHandler may not be a good solution. If the Cloud Scheduler environment doesn't parse structured logs from stdout, the StructuredLogHandler payload will be hard to read. 

But if you can give me an example of what you're printing, that might help too. The [formatting rules](https://cloud.google.com/logging/docs/structured-logging#special-payload-fields) are a bit particular

**Comment by space192** [comment]
Yes sure ! So with the CloudLoggingHandler here is the code : 
```python
from google.cloud.logging.handlers import CloudLoggingHandler
from google.cloud.logging_v2.handlers import setup_logging
import google.cloud.logging
import logging
import json

client = google.cloud.logging.Client()
handler = CloudLoggingHandler(client)
setup_logging(handler)

log = {
        "run_id": best_model["mlflow_run_id"],
        "eval_correlation": best_model["acr_test_correlation"],
        "eval_metric": best_model["acr_test_metric"],
    }
print("Training validation OK")
logging.info(json.dumps(log))
```
And in the journal the only thing I can see is : 
![Screenshot 2023-05-15 at 3 36 36 PM](https://github.com/googleapis/python-logging/assets/44359684/82509042-a588-4186-bbe1-8d1ba57a84a7)

**Comment by daniel-sanche** [comment]
> Yes sure ! So with the CloudLoggingHandler here is the code :

Thanks. Can you try the same with the `StructuredLogHandler` and let me know what you see there?

> And in the journal the only thing I can see is :

Since it seems like the logs are being sent successfully, my hunch is that the log is in Cloud Logging, but it's being filtered from the view you're looking for it in. Can you add this to the Logs Explorer query, and let me know if the logs are showing up there? `resource.type="global"`

![image](https://github.com/googleapis/python-logging/assets/3914119/243ea43d-2dd6-45d8-beb8-a603918191db)

**Comment by space192** [comment]
Oh it finally works ! with the StructuredLogHandler ! Thanks I will now close the issue then !
