### ISSUE TITLE
Environment presubmit tests failing

### ISSUE THREAD

**Issue by parthea** [googleapis/python-logging#778]
There are several presubmits failing in the main branch.

![image](https://github.com/googleapis/python-logging/assets/5184014/c5673598-310c-4826-a49d-715316f27bf8)

https://source.cloud.google.com/results/invocations/87f38db1-9903-4216-a291-a96075abfa46
https://source.cloud.google.com/results/invocations/b7f22e66-9119-4030-bdb1-df4fff96a855
https://source.cloud.google.com/results/invocations/971b93de-e7a6-4ca3-b38b-5fa0283bc5b7
https://source.cloud.google.com/results/invocations/51b69193-5f42-45ca-90b1-2cbbead33613
https://source.cloud.google.com/results/invocations/f1985ec2-99a4-4c90-baa8-ebc459cd3e00
https://source.cloud.google.com/results/invocations/2495424e-8814-4ec1-be52-15e3e9f4e885
https://source.cloud.google.com/results/invocations/cfe100eb-0dfe-47b1-b249-f1d854625761
https://source.cloud.google.com/results/invocations/b3fa7a20-10c7-40e6-95d4-4838746313dc

This was called out in https://github.com/googleapis/python-logging/pull/746

@daniel-sanche Please could you take a look?

**Comment by daniel-sanche** [comment]
We can safely ignore the environment tests for now, it's always been an optional check. I plan to remove them from the kokoro checks for now, and we can re-enable them when we get new dedicated maintainers for the library

**Comment by parthea** [comment]
Fixed via cl/560183841
