### ISSUE TITLE
Dataflow should be a monitored resource

### ISSUE THREAD

**Issue by sayohnahilan** [googleapis/python-logging#780]
#### Environment details

  - OS type and version: `macOS Ventura Version 13.3.1`
  - Python version: `Python 3.8.16`
  - pip version: `pip 23.2.1`
  - `google-cloud-logging` version: `3.1.2`

#### Issue Description
When using python `logging.StreamHandler(sys.stdout)` from within Dataflow, logs are tagged with `resource.type==dataflow_step` and various other `resource.labels` from compute and dataflow are appended such as `dataflow job_id, dataflow job_name, dataflow region, compute resource_id, compute resource_name, compute resource_type`.

However, when using `google.cloud.logging_v2.handlers.CloudLoggingHandler` from within Dataflow, logs are tagged with `resource.type==gce_instance` and other `resource.labels` such as those listed above listed above are lost.

#### Ideal solution
When using `CloudloggingHandler` from within Dataflow, the `resource.type` should equal `dataflow_step` and other information that is propagated when using `StreamHandler` should also propagate.

#### Code example

This code block writes the same log msg twice to google cloud logging from within Dataflow. It demonstrates inconsistent `resource.type` and `resource.labels` when writing log messages using different logging handlers.

<h5 a><strong><code>script.py</code></strong></h5>

```python
import apache_beam as beam
import google.cloud.logging_v2
from google.cloud.logging_v2.handlers import CloudLoggingHandler
import logging
import sys

# Fill in
PROJECT_ID = ""
TEMP_LOCATION = ""
STAGING_LOCATION = ""
REGION = ""
SDK_CONTAINER_IMAGE = "" # image with google-cloud-logging

SETUP_FILE = "setup.py"
LOG_FORMAT = "%(asctime)s %(name)s %(filename)s:%(lineno)d %(levelname)s: %(message)s"


def get_logger(name):
    logger = logging.getLogger(name)
    logger.setLevel(logging.DEBUG)
    client = google.cloud.logging_v2.Client()
    cloud_handler = CloudLoggingHandler(client)
    logger.addHandler(cloud_handler)

    stdout_handler = logging.StreamHandler(sys.stdout)
    stdout_handler.setLevel(logging.DEBUG)
    stdout_handler.setFormatter(logging.Formatter(LOG_FORMAT))
    logger.addHandler(stdout_handler)
    return logger

def process_element(element):
    logger = get_logger(__name__)
    logger.info('A log message to both cloudlogginghandler and streamhandler from within Dataflow')


if __name__ == "__main__":
    pipeline_options = {
        "job_name": "sayohn-python-cloudlogger-issue-with-simplified-logger",
        "project": PROJECT_ID,
        "region": REGION,
        "runner": "DataflowRunner",
        "temp_location": TEMP_LOCATION,
        "staging_location": STAGING_LOCATION,
        "setup_file": SETUP_FILE,
        "sdk_container_image": SDK_CONTAINER_IMAGE,
        "save_main_session": True,
    }

    options = beam.pipeline.PipelineOptions.from_dictionary(pipeline_options)
    pipeline = beam.Pipeline(options=options)
    
    _ = (
        pipeline
        | "make fake data" >> beam.Create(["test"])
        | "write log msg" >> beam.Map(process_element)
    )

    pipeline.run()
```

<h5 a><strong><code>setup.py</code></strong></h5>

```python
import setuptools

setuptools.setup(
    name="dataflow_downloading",
    install_requires=[],
    packages=setuptools.find_packages(),
)
```

**Comment by orilevari** [comment]
Hi I just wanted to check in on if this was triaged and then deprioritized. This feature would still be a big quality of life improvement for us. @daniel-sanche could you give an update if possible?

**Comment by daniel-sanche** [comment]
Hey Ori, @gkevinzheng is the new maintainer of the library, so cc-ing him. 

That said, I believe adding extra automatic  monitored resources isn't a current priority of the library. There are a couple workarounds to your problem though:
- you can use StructuredLogHandler instead, which outputs to stdout like StreamHandler (which means it picks up the proper monitored resource), but includes the additional GCP Logging metadata fields from the CloudLoggingHandler. This is the preferred handler for environments that support stdout capture, with the only downside being that you can't use custom logNames
- alternatively, you can [pass in a custom resource at CloudLoggingHandler init time](https://github.com/googleapis/python-logging/blob/d73cc56ba49d13d2c876c9dbf5c76b2308012161/google/cloud/logging_v2/handlers/handlers.py#L153), so you can manually define how you want your logs to show up

Thanks
