### ISSUE TITLE
Logging: support custom labels in GKE handler.

### ISSUE THREAD

**Issue by ZeeD** [googleapis/python-logging#8]
```client = Client()
handler = client.get_default_handler()
handler.labels = {"foo":"bar"}
logger = logging.getLogger("baz")
logger.addHandler(handler)
logger.warn("qux")
```        

`get_default_handler` returns different implementations of the handler if you are on a local machine, or a GKE cluster.
The latter doesn't support the set of the labels.
Nor it warn about it.

**Comment by daniel-sanche** [comment]
This feature will [now be supported](https://github.com/googleapis/python-logging/pull/264) for the StructuredLogHandler and the CloudLoggingHandler in the upcomming feature release (v2.4.0).

Unfortunately this change isn't coming to the default ContainerEngineHandler or AppEngineHandler, as we plan to remove them in favor of StructuredLogHandler and CloudLoggingHandler in the next major (v3.0.0) release. To use this feature on GKE, you'll have to set a different handler type:

```
import logging
import google.cloud.logging
from google.cloud.logging.handlers import StructuredLogHandler

handler = StructuredLogHandler(labels={"foo":"bar"})
logger = logging.getLogger()
logger.addHandler(handler)
logger.warn("qux", extra={"labels":{"another-label":"baz"}})
```
