### ISSUE TITLE
Issue while mapping the Log Entry response

### ISSUE THREAD

**Issue by yokeshrana** [googleapis/python-logging#802]
Constantly seeing the issue in google cloud logging python library (is not an instance of LogEntry) while retrieving the logs .

#### Environment details

 Name: google-cloud-logging
Version: 3.8.0
Summary: Stackdriver Logging API client library

#### Steps to reproduce

  1. Use the list entries functionality 
  2. Observing this error 
  **ERROR THROWN => 

**""

labels {

 key: "session_id"

 value: "#############"

}

log_name: "projects/########/logs/dialogflow-runtime.googleapis.com%2Frequests"

receive_timestamp {

 seconds: 1697655846

 nanos: 99821713

}

 is not an instance of LogEntry

"****

**Comment by gkevinzheng** [comment]
@yokeshrana I need more debugging output to better troubleshoot the issue. The proto you provided looks like an instance of `LogEntry`, but to better troubleshoot the issue, I need to know the type of object being received. You can either use `pdb`, or go to the root directory where you have installed `google-cloud-logging`, and in `google/cloud/logging_v2/_gapic.py`, temporarily add in a print/log statement for the type of `entry` above the line https://github.com/googleapis/python-logging/blob/c4471758e1efee0e3599b08969449b2ce71bd1b4/google/cloud/logging_v2/_gapic.py#L114

**Comment by gkevinzheng** [comment]
@yokeshrana I am closing this issue for now, feel free to reopen this if the issue still persists.
