### ISSUE TITLE
Enabling logging causes GAE application to stall

### ISSUE THREAD

**Issue by matthiasgeihs** [googleapis/python-logging#803]
I am running a Google App Engine application in Python Standard Environment since a while and everything was running fine.
Yesterday, after deploying some changes, the app would stall completely without any error trace printed to the logs. The instance just hangs immediately after receiving a request.

I did a lot of debugging, and finally figured that when I disable cloud logging, everything goes back to normal. I can reproduce the same behavior on my local system. The weird thing is that it doesn't stall at a logging call, but when it makes a request to the cloud datastore afterwards, which it also relies on.

This looks like a thread locking issue as it is timing depending (goes away when debugging step by step, or when placing sleep after logging) and stops the application from responding completely.

In included a minimal code example that reproduces the erroneous behavior. This is a pressing issue (as I can't use GAE with logging currently), so any help / insights is appreciated.

#### Environment details

  - OS type and version: GAE Python Standard Environment
  - Python version: python312
  - pip version: determined by GAE environment
  - `google-cloud-logging` version: 3.8.0

#### Steps to reproduce

Run example below.
Prints `INFO:root:Retrieving sample`, but does not print `done`.
(Runs fine if inserting `time.sleep(1)` after the first logging call.)

#### Code example

`main.py`
```python
from flask import Flask
from google.cloud import datastore
import logging, google.cloud.logging

# Setup logging.
logging.basicConfig(level=logging.INFO)
client = google.cloud.logging.Client()
client.setup_logging()

app = Flask(__name__)
db_client = datastore.Client()

@app.route('/')
def root():
    logging.info(f"Retrieving sample")
    key = db_client.key("Task", "sampleTask")
    feed = db_client.get(key)
    logging.info("done")
    return "Success"

# Local main
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8080, debug=True)
```

`app.yaml`
```yaml
runtime: python312

handlers:
- url: /static
  static_dir: static

- url: /.*
  secure: always
  script: auto
```

`requirements.txt`
```
Flask==3.0.0
google-cloud-datastore==2.18.0
google-cloud-logging==3.8.0
```

#### Stack trace
No stack trace as process just hangs completely until terminated.

**Comment by gkevinzheng** [comment]
I just tried your code example, along with the yaml and `requirements.txt` in a fresh App Engine instance and can't reproduce it.

**Comment by gkevinzheng** [comment]
@matthiasgeihs If you're having trouble with threading and blocking behavior, I recommend using the `StructuredLogHandler` class. It logs to stdout, which then gets propagated to Cloud Logging via an agent.

**Comment by matthiasgeihs** [comment]
@gkevinzheng Thanks for coming back to this. I couldn't find the time to test this again. Planning to report back once I can. Thanks for the suggestion.

**Comment by matthiasgeihs** [comment]
The issue still persists for me :(

Also tried with a different account. Same result. I am really puzzled.

The following would be the workaround using `StructuredLogHandler`, correct? @gkevinzheng 
```python
from google.cloud.logging.handlers import StructuredLogHandler
handler = StructuredLogHandler()
logging.basicConfig(level=logging.INFO, handlers=[handler])
```

**Comment by gkevinzheng** [comment]
@matthiasgeihs Yeah that should add `StructuredLogHandler` as a handler. Unfortunately I can't reproduce the hanging issue on my end.

**Comment by matthiasgeihs** [comment]
Ok, I guess there is not much more that can be done here at this point. Feel free to close the issue.
