### ISSUE TITLE
`CloudLoggingHandler` violates the contract of its parent class (`StreamHandler`) by not calling the formatter provided by `setFormatter`

### ISSUE THREAD

**Issue by JakeSummers** [googleapis/python-logging#809]
#### Environment details

  - Python version: `python --version`: `Python 3.10.12`
  - `google-cloud-logging` version: `poetry show google-cloud-logging`: `3.8.0`

#### Issue

The `CloudLoggingHandler` extends `logging.StreamHandler`.  In our code we use both depending on what the target logging environment is (largely due to [waiting on this issue](https://partnerissuetracker.corp.google.com/issues/198064329#comment29)).  

The `StreamHandler` has a `setFormatter` method that allows you to format your log messages.

The `CloudLoggingHandler` extends `StreamHandler` but violates its contact by not calling the `format` method in its own `emit` method 

We are integrating with [structlog](https://www.structlog.org/en/stable/) and using the formatter to turn complex objects (nested objects, numpy arrays, etc) into json/strings.  Since the formatter is not called, we get cryptic error messages, like this;

```
Failed to submit 3 logs.
```

![image](https://github.com/googleapis/python-logging/assets/5657503/2804053c-0b9c-43d5-9abf-cf4975190911)

We can probably fix this by pre-formatting the messages but it would be preferable if the `CloudLoggingHandler` honored its contract.

**Comment by JakeSummers** [comment]
A very ugly but possible workaround is to patch the class like this: 

```python
class PatchedCloudLoggingHandler(CloudLoggingHandler):

    def __init__(self,
        client,
        transport,
        resource,
        ):
        super().__init__(client=client, transport=transport, resource=resource)

    def emit(self, record):
        msg = self.format(record)
        record.msg = json.loads(msg)
        super().emit(record)
```

**Comment by gkevinzheng** [comment]
Could you provide some code samples that I can use to reproduce this issue?
