### ISSUE TITLE
document django middleware

### ISSUE THREAD

**Issue by maclek** [googleapis/python-logging#844]
The django middleware isn't documented anywhere as far as I can see.

It needs to be documented here: https://cloud.google.com/logging/docs/setup/python#write_logs_with_the_standard_python_logging_handler

There are lots of people reporting the logs don't have an http info and this could certainly be a root cause.

Perhaps it was documented at one point? See this issue here:

https://github.com/googleapis/python-logging/issues/677

Or maybe we're all just looking through the source.

Thanks.

**Comment by gkevinzheng** [comment]
@maclek I am currently working on documenting Django integrations. Is there anything else that you have found that needs to be done in other to get them to work, other than adding the middleware to `settings.py`?

**Comment by maclek** [comment]
No, just the middleware

**Comment by pataquets** [comment]
@gkevinzheng I see no specific recommendation about where in the middleware chain should this one be placed. I see in some issues that it's placed topmost and I guess it's the right thing to do, but no explicit recommendation in the docs.
Is there anything else to account for? I'm open to sending a PR with the clarification, provided someone gives me the correct advice.
