### ISSUE TITLE
`from google.cloud import logging` collides with `logging` from standard library

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-logging#88]
Also, an issue with `from google.cloud import logging` is that it collides with the `logging` standard library, and they are often [going to be used together](https://cloud.google.com/logging/docs/setup/python#connecting_the_library_to_python_logging). Right now we tell users to import as `import google.cloud.logging` and use the full path in their code. I wonder if it would make sense to rename the library to `google.cloud.cloudlogging` or something so there's no naming conflict

_Originally posted by @Daniel-Sanche in https://github.com/googleapis/python-logging/pull/83#discussion_r515238862_

**Comment by Daniel-Sanche** [comment]
After getting some feedback, I'm going to hold off on this.  We don't want to confuse existing customers more than needed
