### ISSUE TITLE
Create a google-cloud-audit virtual package

### ISSUE THREAD

**Issue by rsalmond** [googleapis/python-logging#9]
**Is your feature request related to a problem? Please describe.**
Yes, users of the logging module are [opening spurious bugs](https://github.com/googleapis/google-cloud-python/issues/5322) and [conflating issues](https://github.com/googleapis/google-cloud-python/issues/3218) due to the lack of a clear path to deserializing AuditLog objects

Without the presence of a python compiled copy of [the AuditLog protocol definition](https://github.com/googleapis/googleapis/blob/master/google/cloud/audit/audit_log.proto), users of the logging client library cannot deserialize [audit log entries](https://cloud.google.com/logging/docs/audit/understanding-audit-logs) that have been returned by the logging API in the form of a serialized `proto_payload`.

Last summer @tseaver [rightly points out](https://github.com/googleapis/google-cloud-python/issues/5514#issuecomment-399200147) that it cannot be expected for the logging module to assume the type of a field declared as `Any`. However given that the [LogEntry protocol definition](https://github.com/jmorenog/googleapis-googleapis/blob/2b09d506fa548359bec747ef7757e43dd58e348f/google/api/servicecontrol/v1/log_entry.proto#L54-L57) suggests that AuditLog is the _only_ currently accepted type it seems a poor developer experience for users to need to understand protobuf well enough to download and compile the definition themselves.

 **Describe the solution you'd like**
The creation of a new `google-cloud-audit` virtual package containing the python version of the AuditLog protocol definition.

 **Describe alternatives you've considered**
As a workaround I have followed [this users link to stackoverflow](https://github.com/googleapis/google-cloud-python/issues/5313#issuecomment-399237060) and compiled the AuditLog pb definition into my project manually.

**Comment by bytesandwich** [comment]
Has there been any progress on this @tseaver @lukesneeringer ? I'm trying to deserialize exported Audit logs that I get from pubsub, and it seems impossible without this protobuf being compiled. 

```python
    from google.cloud.logging_v2.proto.log_entry_pb2 import LogEntry
    from google.cloud.audit import AuditLog
    import google.protobuf.json_format
    google.protobuf.json_format.Parse(bytes_message, LogEntry(), ignore_unknown_fields=True)
```
Do I really have to clone repos just to compile the schema for this nested field?

**Comment by busunkim96** [comment]
Ah yep, we can definitely do that - we have a few other packages that are just generated `_pb2.py` files.

**Comment by bytesandwich** [comment]
hi @busunkim96 thank you very much! Could you also update the proto definition for that package? For instance `AuditLog.AuthenticationInfo` is [specified](https://cloud.google.com/logging/docs/reference/audit/auditlog/rest/Shared.Types/AuditLog#authenticationinfo) to contain `principalEmail` and `authoritySelector`, but the [checked in proto](https://github.com/googleapis/googleapis/blob/master/google/cloud/audit/audit_log.proto#L93) is missing `authoritySelector`.

**Comment by busunkim96** [comment]
@bytesandwich Sorry for the late response, it looks like the protos have been updated with all the newer fields. https://github.com/googleapis/googleapis/blob/master/google/cloud/audit/audit_log.proto#L93

**Comment by tseaver** [comment]
@busunkim96 Do we have a place where generation of a library from that proto would live?

**Comment by busunkim96** [comment]
@tseaver I haven't filed a request for the repo yet, but I was planning on repo name `googleapis/python-audit` and package name  `google-cloud-audit`.

**Comment by busunkim96** [comment]
To avoid naming conflicts with some future service named "Google Cloud Audit" I am releasing the the package with the name `google-cloud-audit-log` in the repo `python-audit-log`. The package with the pb2 will be out to PyPI by the end of the week.

**Comment by busunkim96** [comment]
Released.

Repo: https://github.com/googleapis/python-audit-log
PyPI: https://pypi.org/project/google-cloud-audit-log/
