### ISSUE TITLE
[cloud.logging] CloudLoggingHandler does not set logName in Cloud Functions/Run environment

### ISSUE THREAD

**Issue by evil-shrike** [googleapis/python-logging#902]
I'm setting up CloudLoggingHandler with a custom name to have an ability to filter log entries in Cloud Logging. But despite method I use to setup it up it doesn't work - 

Given a Cloud Function (deployed as http triggered):

`logger.py`
```
import os
LOGGER_NAME = 'Sample'

logging.basicConfig(
    format='[%(asctime)s][%(name)s][%(levelname)s] %(message)s',
    level=logging.INFO,
    datefmt='%H:%M:%S'
)
loglevel = os.environ.get('LOG_LEVEL', 'DEBUG')
loglevel = logging.getLevelName(loglevel)

logger = logging.getLogger(LOGGER_NAME)
logger.setLevel(loglevel)

if bool(os.getenv('K_SERVICE')):
  import google.cloud.logging
  from google.cloud.logging.handlers import CloudLoggingHandler, setup_logging

  client = google.cloud.logging.Client()
  handler = CloudLoggingHandler(client, name=LOGGER_NAME)
  handler.setLevel(loglevel)
  logger.addHandler(handler)
  # also tried these:
  #setup_logging(handler)
  #client.setup_logging()
```

`main.js`
```
from logger import logger

def main(request):
  logger.info('Cloud Function is called')
  return ""
```

So I create a CloudLoggingHandler with my log name and added it to my Python logger. This is what suggested to do in official doc: https://cloud.google.com/python/docs/reference/logging/latest/handlers-cloud-logging
But it doesn't work in Cloud Functions

Here's how my log entry look like:
<img width="628" alt="image" src="https://github.com/googleapis/google-cloud-python/assets/1203230/bfb1d222-1981-4012-aaba-5d1a366286a9">

The logname field is still default stdout.

**Comment by gkevinzheng** [comment]
@evil-shrike What code are you running on the Cloud Function that gives you issues with not seeing all the logged messages?

**Comment by bhshkh** [comment]
Closing the issue as the reporter has not responded to the query
