### ISSUE TITLE
Argument of type "type[SyncTransport]" cannot be assigned to parameter "transport" of type "Transport" in function "__init__"

### ISSUE THREAD

**Issue by AdeelK93** [googleapis/python-logging#929]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-logging/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version` 3.12.4
  - pip version: `pip --version` 24.1.2
  - `google-cloud-logging` version: `pip show google-cloud-logging` 3.11.0
  - pyright version: 1.1.374

#### Steps to reproduce

Same as #901 - but, now there's a type error even if you don't provide a Transport in 3.11. Previously, omitting the argument wouldn't yield a type error.

#### Code example

```python
import google.cloud.logging
from google.cloud.logging.handlers import CloudLoggingHandler
from google.cloud.logging.handlers.transports import SyncTransport

client = google.cloud.logging.Client()
handler = CloudLoggingHandler(client, name="LOGGER_NAME", transport=SyncTransport)
```

#### Stack trace
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/69d79d89-edff-43e7-9ea9-c9c876c22e59">

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by joshtemple** [comment]
For what it's worth, I would actually prefer for `Transport` to be passed as an instance instead of as a class. Having to create a custom subclass of the Transport class just to adjust the config values for things like `grace_period` or `batch_size` (in the case of `BackgroundThreadTransport`) feels pretty clumsy.
