### ISSUE TITLE
Clean up `docs/snippets.py` file

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-logging#93]
This file should be moved into the samples directory `samples/snippets` or removed entirely. It is used to add code to `usage.rst` but is not tested at the moment.

https://cloud.google.com/logging/docs/samples

**Comment by Daniel-Sanche** [comment]
This was addressed in https://github.com/googleapis/python-logging/pull/140. The snippets have been moved to `samples/snippets/usage_guide.py` tests have been added
