### ISSUE TITLE
Default configuration of google-cloud-logging broken for Vertex AI Online Prediction Endpoint

### ISSUE THREAD

**Issue by racinmat** [googleapis/python-logging#941]
#### Environment details

The environment is custom container in Vertex AI Online Prediction

  - OS type and version: `Debian GNU/Linux 12 (bookworm)` in docker image
  - Python version: `Python 3.11.7`
  - pip version: `pip --version`
  - `google-cloud-logging` version: 
  ```
  Name: google-cloud-logging
  Version: 3.11.2
  Summary: Stackdriver Logging API client library
  Home-page: https://github.com/googleapis/python-logging
  Author: Google LLC
  Author-email: googleapis-packages@google.com
  License: Apache 2.0
  Location: /usr/local/lib/python3.11/site-packages
  Requires: google-api-core, google-auth, google-cloud-appengine-logging, google-cloud-audit-log, google-cloud-core, 
  grpc-google-iam-v1, opentelemetry-api, proto-plus, protobuf
  Required-by: 
  ```

#### Steps to reproduce

  1. create a custom container following https://cloud.google.com/vertex-ai/docs/predictions/custom-container-requirements?hl=en
  2. use the automatic configuration in the python webserver according to https://cloud.google.com/python/docs/reference/logging/latest/std-lib-integration#automatic-configuration

#### Code example

the following code is MWE of working webserver with the cloud logging set up
```python
import logging
import os

import uvicorn
from fastapi import FastAPI, Request, Response
import google.cloud.logging

app = FastAPI()

client = google.cloud.logging.Client()
client.setup_logging(resource="gae_app")

logger = logging.getLogger(__name__)


@app.get(os.environ.get('AIP_HEALTH_ROUTE', '/health'), status_code=200)
async def health():
    logger.info('called health and logging')
    return {"status": "healthy"}


@app.post(os.environ.get('AIP_PREDICT_ROUTE', '/predict'), status_code=200)
async def predict(request: Request):
    body = (await request.body()).decode('utf-8')
    return {"instances": [{"body": body}]}


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8080)
```

#### Stack trace
There is no stacktrace, the logging is just shown wrogly.
![image](https://github.com/user-attachments/assets/ba1124f0-a89a-410c-ae91-1e54db525541)

#### Expected behavior

The logs would appear correctly and the [`CloudLoggingHandler`](https://cloud.google.com/python/docs/reference/logging/latest/handlers-cloud-logging#google.cloud.logging_v2.handlers.handlers.CloudLoggingHandler) is used

#### Actual behavior

The [`StructuredLogHandler`](https://cloud.google.com/python/docs/reference/logging/latest/handlers-structured-log#google.cloud.logging_v2.handlers.structured_log.StructuredLogHandler) is used instead.

The Vertex AI Online Prediction does not support structured logging, which is the root cause.

The issue is that https://github.com/googleapis/python-logging/blob/v3.11.2/google/cloud/logging_v2/client.py#L123 infers the project of underlying google internal project within google internal tenant, and not my GCP project, and https://github.com/googleapis/python-logging/blob/v3.11.2/google/cloud/logging_v2/client.py#L377 infers the `_GKE_RESOURCE_TYPE` because the Vertex AI Online Prediction really runs in GKE, but due to structured logging not working, it just sends everything to stderr, which is interpreted as error.

#### Workaround

Set the project and resource as a global resource manually:
```python
import google.cloud.logging
from google.cloud.logging_v2.handlers._monitored_resources import _create_global_resource
project = os.environ.get("AIP_PROJECT_NUMBER")
client = google.cloud.logging.Client(project=project)
client.setup_logging(resource=_create_global_resource(project))
```

**Comment by gkevinzheng** [comment]
@racinmat This is an edge case issue with the lack of support on a very specific Cloud Platform. I don't think we want to add support for this specific edge case issue, which is very likely to be temporary, when the workaround you provided works fine for creating what you wanted.
